name: getx_youtube_streaming
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.1
  equatable: null
  get: null
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: null

flutter:
  uses-material-design: true
